### ISSUE TITLE
UI/UX enhancements

### ISSUE THREAD

**Issue by josezy** [josezy/ikaro#18]
* [x] attitude / compass indicators [*](https://github.com/MrFoxPro/react-flight-indicators) (done by a6ec386495fc4b0a47a78ba632c15cf5b82cf993)
* [x] flight time (done by #20)
* [x] battery level (done by #21)
* [x] ground speed (done by #22)
* [x] GPS Status (sat count, lock, hdop, vdop) (done by #22)
* [x] flight distance (done by #27)
* [ ] ~home position [MAV_CMD_GET_HOME_POSITION](https://mavlink.io/en/messages/common.html#MAV_CMD_GET_HOME_POSITION)~
* [ ] ~distance to home~
* [x] goto point (done by 4db4fe5529ba1371253b44d15e337701dd3b55b3)
* [x] log window for [STATUSTEXT](https://mavlink.io/en/messages/common.html#STATUSTEXT) msg and COMMAND_ACK?) (done by #35)
* [x] send heartbeat (1Hz) (done by #36)
* [x] show green/red dot meaning there is heartbeat
* [x] show/~change~ flight mode (done by 7f1cdbff7e28e75f2a985f965c4b68bfa2e739af)
* [x] pause button to stop any drone movement (done by 145ab37671bd2410a3ae3547d69b9a7c253939a9)
* [x] make map center drone (be careful with performance) (done by 3e2b02829f5fc5f4ec073de867ce9186344444dc)
